---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tech-talk
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/TechTalkFridays/tech-talk-cd.git
    targetRevision: develop
    path: tech-talk-chart
    helm:
      valueFiles:
      - helm_vars/engineering/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
