apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  name: ingress-argo
  namespace: argocd
spec:
  rules:
  - host: {{ .Values.ingressHost }}
    http:
      paths:
      - backend:
          serviceName: argocd-server
          servicePort: 443
        path: /
